language: python
python:
  - "3.6"
script:
  - coverage run practicaADN3.py

before_install:
  - python -m pip install --upgrade pip
install:
  - pip install -r requirements.txt

after_success:
  - coveralls